[build]
  command = "npm run build"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
  # REQUIRED: Set these in Netlify Dashboard > Site Settings > Environment Variables
  # COINBASE_WEBHOOK_SECRET = "whsec_your_secret_from_coinbase"
  # SMTP_HOST = "smtp.ionos.com"
  # SMTP_PORT = "587"
  # SMTP_USER = "hello@runeflow.xyz"
  # SMTP_PASS = "your_email_password"
  # FROM_EMAIL = "hello@runeflow.xyz"

# RuneFlow API routes redirect to RuneFlow Railway service
[[redirects]]
  from = "/api/v1/*"
  to = "https://runeflow-api.up.railway.app/api/v1/:splat"
  status = 200

# RuneRush API routes redirect to RuneRush Railway service
[[redirects]]
  from = "/api/*"
  to = "https://runeflow.up.railway.app/api/:splat"
  status = 200

[[redirects]]
  from = "/capture-email"
  to = "/.netlify/functions/capture-email"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/admin/emails"
  to = "/.netlify/functions/admin-emails"
  status = 200

[[redirects]]
  from = "/admin/test-smtp"
  to = "/.netlify/functions/test-smtp"
  status = 200

[[redirects]]
  from = "/auth/twitter/callback"
  to = "/.netlify/functions/twitter-callback"
  status = 200

# Coinbase Commerce webhook
[[redirects]]
  from = "/webhook/coinbase"
  to = "/.netlify/functions/coinbase-webhook"
  status = 200

# Ensure trailing slash for runerush directory
[[redirects]]
  from = "/runerush"
  to = "/runerush/"
  status = 301
  force = true

# DO NOT redirect runerush files - let them serve normally
# Only use this if you have a React/Vue SPA in runerush
# [[redirects]]
#   from = "/runerush/*"
#   to = "/runerush/index.html"
#   status = 200
#   conditions = {Language = ["en"], Country = ["US"]}

# Note: Remove the catch-all redirect as it will break runerush
# Only use if main site is SPA
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
