[build]
  command = "npm run build-static"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
  # REQUIRED: Set these in Netlify Dashboard > Site Settings > Environment Variables
  # COINBASE_WEBHOOK_SECRET = "whsec_your_secret_from_coinbase"
  # SMTP_HOST = "mail.runeflow.xyz"
  # SMTP_PORT = "587"
  # SMTP_USER = "hello@runeflow.xyz"
  # SMTP_PASS = "your_email_password"
  # FROM_EMAIL = "hello@runeflow.xyz"

# API routes redirect to functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/capture-email"
  to = "/.netlify/functions/capture-email"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

# Coinbase Commerce webhook
[[redirects]]
  from = "/webhook/coinbase"
  to = "/.netlify/functions/coinbase-webhook"
  status = 200

# Catch-all for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
