[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
NODE_ENV = "production"
PORT = { default = "8080" }
HOST = "0.0.0.0"

[[services]]
name = "runeflow-coming-soon"
