[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start:debug"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[variables]
NODE_ENV = "production"
HOST = "0.0.0.0"
